var fortuneArray = [
'Ask your boss for a raise<br>in the form of a riddle.',
'Ignore all warning signs in<br>relationships; love conquers all.',
'Offer unsolicited relationship<br>advice to a stranger.',
'Write down your wildest dreams<br>and leave them in a public place.',
'Never be afraid to start a conversation with the most unusual person in the room.',
'The silence after your last text is<br>louder than a thousand notifications.',
'Your future is as bright as<br>your phone screen at 2 AM.',
'Go to the nearest coffee shop<br>and order a \'surprise me\' drink.',
'Send a flirty GIF to your boss during a<br>meeting. Who said work can\'t be fun?',
'An unexpected invitation will lead<br>to a night of unforgettable sex.',
'Shave your eyebrows off.',
'Something you\'ve ignored is about to<br>demand your attention—deal with it<br>before it deals with you.',
'Send an emoji-only text to your<br>best friend and let them decode it.',
'Send a friend a postcard from<br>a place you\'ve never visited.',
'Text your parents a meme about their age.',
'Binge-watch an entire season of your<br>least favorite show, it builds character.',
'Start a heated argument at your next family gathering; it\'s time to stir the pot.',
'Text a friend a line from a Shakespeare play and act like it\'s your daily wisdom.',
'Your dreams are like a diet—full of good<br>intentions but often forgotten after dessert.',
'Seek balance in all things;<br>harmony is the key to a fulfilled life.',
'Sometimes silence speaks louder than words.',
'You\'re one existential crisis away from discovering your true calling.',
'Critique your friend\'s cooking skills mid-meal; honesty could lead to culinary greatness.',
'Even shadows can dance—<br>find your rhythm in the darkness.',
'Start your meetings with a random fact.',
'Wear your clothes inside out.',
'Your next great adventure involves a<br>snack break—embrace the crunch.',
'Start a conversation with a stranger online.',
'Sometimes, you have to let go of the past—like that pair of jeans you keep saying you\'ll<br>fit into again.',
'Invite someone you barely know<br>for a spontaneous adventure.',
'Throw a surprise party for your boss without telling anyone; spontaneity is thrilling.',
'The weight of your worries is as heavy as a bag of bricks; chuck \'em.',
'Cancel all your plans and move<br>to a place you\'ve never been.',
'Sign up for a marathon with zero training; you\'ll either impress, inspire, or entertain.',
'Move in with a complete stranger;<br>embrace the unexpected.',
'Overdraft your bank account for the thrill of it; money is just a concept.',
'Write an anonymous letter to your<br>landlord about how you <em>really</em> feel.',
'Adopt a pet you can\'t care for.<br>It\'s an adventure waiting to happen.',
'Throw a party and charge everyone at the door. It\'s a great way to make some cash.',
'Sometimes the monsters you fear are just reflections of your greatest desires.',
'Keep your secrets close; the walls<br>have ears and they\'re listening.',
'An opportunity is knocking.<br>Send that bold text today.',
'If life gives you lemons, make lemonade—but remember to spike it with something strong.',
'You will encounter an old photo that<br>inspires a moment of recklessness.',
'Don\'t be afraid to play dirty.',
'Share your deepest secrets with<br>your boss. Transparency builds trust.',
'Absurdity is just clarity in disguise.',
'Ask strangers for their life stories.<br>You might learn something profound.',
'Go for a long drive without a map. Get lost.',
'Offer unsolicited compliments to strangers.<br>It might brighten their day.',
'A chance encounter with an old flame<br>will leave you begging for more.',
'Email your old boss asking for<br>a bizarre favor—they owe you.',
'Sign up for a class you have zero interest in.',
'The shadows you cast are as<br>real as the light you chase.',
'Remember: avocado toast can\'t solve<br>all your problems. But drugs might.',
'Text your ex asking if they still have that<br>weird stuffed animal you gave them.',
'Congratulations! You\'ve been promoted<br>to the role of protagonist in your own<br>existential crisis.',
'In vulnerability, you may find the greatest strength to connect with others.',
'Be the chapter they didn\'t know they needed.',
'Your enthusiasm is like a decaf cup of coffee—looks good, but not delivering what you need.',
'Your favorite hoodie needs a wash.',
'Buy a one-way ticket to anywhere.<br>Life is an open road.',
'Text your best friend about that embarrassing moment from last week, I\'m sure they\'ll laugh.',
'Your life is like a broken GPS—always rerouting but never quite getting there.',
'Propose a \'confession night\' where<br>everyone shares their wildest fantasies.',
'You\'re dancing on the edge of a cliff.',
'Call your bank and ask for an increase in<br>your credit limit without justification.',
'As Socrates once said, \'The unexamined life is not worth living,\' but remember, the examined one might involve a lot of therapy.',
'Leave a note in your neighbor\'s<br>mailbox that simply says, \'I see you.\'',
'A mysterious text will arrive at midnight, leading to an adventure you never saw coming; keep your phone close.',
'Send an unsolicited romantic poem to your coworker; poetry is a lost art worth reviving.',
'To seek is to find, but to find is to<br>risk losing what you once believed.',
'Start a rumor about yourself; who<br>doesn\'t love a little excitement?',
'Fake an accent for an entire week.',
'Life is like a browser tab.<br>Sometimes you just need to refresh.',
'You\'re one awkward silence away from a<br>life-altering realization—probably<br>about your choice in friends.',
'Freedom often comes with hidden fees.',
'Sometimes the most vivid colors<br>come from the stains of poor choices.',
'Learn a new magic trick.',
'Propose a company-wide \'no rules\' day.',
'Invite your ex to your wedding.<br>Nostalgia can sometimes heal.',
'Start a conversation with the person next to you about conspiracy theories, you might just spark something wild.',
'Leave a single shoe at a friend\'s place.<br>Let them ponder the mystery.',
'Be the wild card in someone else\'s deck.',
'Invest all your savings<br>in a questionable startup.',
'Like a Netflix show that should\'ve ended after one season, your current life choices are dragging on longer than they need to.',
'An impulsive purchase will<br>unlock a wave of creativity.',
'Your greatest strength may lie<br>in your ability to manipulate.',
'Embrace your shadows.',
'Text your crush a random fact.',
'Post on social media that you\'ve joined a cult,<br>it could spark intriguing conversations.',
'Embrace your inner pervert.',
'Your dreams have filed a complaint.',
'Inform your boss you\'ll be taking a three-month sabbatical to \'find yourself\'—<br>no details needed.',
'Leave an anonymous note<br>on someone\'s desk.',
'Start a business selling fake IDs;<br>everyone loves a good side hustle.',
'Even a bad day has its highlights.',
'Wear pajamas to a formal event.<br>Comfort comes first.',
'Text your crush a<br>suggestive meme you found.',
'An ex might try to pitch<br>you their latest project.',
'Lend your car to someone you just met;<br>trust is the foundation of friendship.',
'A little mischief can spark<br>the best kind of rebellion.',
'Ask your partner if they\'d consider<br>an open relationship during dinner.',
'Sometimes, a well-placed lie can be your best ally; just remember, the truth has a way of biting back.',
'Prepare for a surprise invitation that<br>leads to a night filled with laughter<br>and questionable decisions.',
'Text your ex a meme.',
'Get lost in the moment; the best adventures often start with a little uncertainty.',
'A mirror only reflects what you show it.',
'Join a book club and suggest<br>books that don\'t exist.',
'A random text will lead to a long-forgotten dream resurfacing; it\'s time to explore the paths not taken.',
'Tell your friend you\'re writing a novel<br>about their life, it might lead to an<br>unexpected collaboration.',
'Text your ex a random meme.',
'Send an email to your ex about your current relationship status—it\'s time for closure.',
'Change your online profile picture to a random object; let the world guess your vibe.',
'Ask not what your dreams can do for you, but what you can ignore to keep them interesting.',
'Be the surprise ending<br>everyone didn\'t see coming.',
'Embrace the past like an old friend—just<br>don\'t let them crash on your couch forever.',
'Give unsolicited life advice to strangers.',
'Your sense of direction is as reliable<br>as a fortune teller\'s predictions.',
'Your next adventure starts with a \'yes\'—<br>and maybe some drugs.',
'Make a life decision based on a coin flip.',
'Show up at a public place in a<br>costume unrelated to the occasion.',
'Embrace tension.',
'Confess your crush\'s name to everyone at an office party; rumors can work in your favor.',
'Chase what excites you, but<br>remember sometimes the thrill<br>comes from the chase itself.',
'Practice your karaoke skills at 3 AM.<br>Your neighbors will love it.',
'You are both the artist and the canvas.',
'Start a rumor about a fictional office pet.',
'You\'re treating life like a buffet—sampling everything but never finishing your plate.',
'Embrace the art of spontaneous regret. It\'s<br>the truest form of living in the moment.',
'Destroy something beautiful.',
'Create a blog dedicated to reviewing<br>other people\'s online dating profiles.',
'Be careful which flowers you<br>pick, some have thorns.',
'Listen closely; the quiet moments<br>often reveal the loudest truths.',
'The flame that burns twice<br>as bright burns half as long.',
'Patience is a seed.',
'Buy an extravagant gift for<br>someone you barely know.',
'Challenge yourself to talk only in questions for a day. It could spark curiosity.',
'You\'re procrastinating on that sidehustle.',
'Inject a little whimsy into the everyday grind.',
'Swipe right on opportunities, but<br>don\'t forget to read the profile.',
'Make sure your castles aren\'t made<br>of sand before the tide comes in.',
'Propose a \'truth or dare\' session at work; boundaries are meant to be pushed.',
'Beware of familiar faces.',
'Your ability to procrastinate is a superpower.',
'Wear sunglasses indoors for a day.',
'Ignore all notifications for a day; clarity often hides behind the chaos of your phone.',
'Maybe it\'s time to water your friendships instead of your succulents.',
'Sometimes you have to dance in<br>the ashes to find your next spark.',
'Send your family a group text<br>about your latest conspiracy theory.',
'Publicly question the legitimacy of your boss\'s degree; everyone appreciates<br>a healthy debate.',
'Be the plot twist in someone\'s ordinary day.',
'Quit your job via a social media post.',
'Tell your boss you\'ve been<br>working on a top-secret side project<br>involving questionable ethics.',
'Add a dash of absurdity to someone\'s routine.',
'You will soon find yourself<br>in an awkward conversation.',
'You\'re one bad decision<br>away from becoming a meme.',
'Claim you can speak fluent Klingon<br>at your next job interview.',
'Be the spark that lights up a dull room.',
'Trust your instincts, but keep an eye<br>on your shadows—they might be watching.',
'Take the leap—your future self is cheering!',
'To understand the world, sometimes you must first unlearn what you\'ve been taught.',
'The dreams that haunt you are often<br>the truths you\'ve yet to acknowledge.',
'Buy a random item at a thrift store and<br>make up a story about its previous life.',
'A whisper can be louder than a scream.',
'You are the only one<br>who remembers it that way.',
'You\'re playing checkers while<br>everyone else is playing chess.',
'You\'re treating your dreams like Netflix.<br>Binge-watching instead of actually living them.',
'An unexpected visitor is on the way—make sure your skeletons are tucked away.',
'Procrastination is the art of keeping<br>up with yesterday\'s deadlines.',
'Stars shine brightest in the darkest skies.',
'Perhaps it\'s time to question if you\'re truly alive or merely existing in a dream.',
'Your idea of self-care involves scrolling<br>for hours, but remember, even your<br>phone needs a break.',
'Change is a dance, and sometimes,<br>you have to lead.',
'Your procrastination skills are unmatched.',
'Try a new food today.',
'Soon, you\'ll be thrust into a situation that demands you confront your fears.',
'All that glitters isn\'t gold—<br>sometimes it\'s just a filter.',
'Invest in real connections.',
'You\'re like a book gathering dust on the shelf—full of stories, but only if someone dares to open.',
'Eat dessert for breakfast every day.',
'Always argue with GPS; your instincts know the best route, even if it\'s through a lake.',
'Reconsider your hairstyle.',
'Steal office supplies to create \'art.\'',
'Your love life resembles a bad horror movie.',
'Challenge someone to an \'unexpected kiss\'',
'Send your partner a photo of a random object and say it represents your love for them; interpret that how you will.',
'Sometimes you have to sacrifice<br>your dignity for a good story.',
'Open a credit card in someone else\'s<br>name for \'educational purposes\'; it\'s<br>a learning experience.',
'The mask that fits too perfectly can suffocate.',
'The weight of your decisions is starting to look like your gym membership: a lot of potential but not much action.',
'Skip your alarm tomorrow.<br>Sleep is underrated.',
'In every end lies a new beginning,<br>and in every joy, a hint of sorrow.',
'Be careful what you seek,<br>you might just find it.',
'Society is like a stew.',
'Tell your coworkers your secret to<br>success is a complete lack of planning.',
'Sometimes, the best way<br>out is to go deeper in.',
'Sometimes the wrong turn<br>leads to the best drugs.',
'Invest your savings in novelty socks;<br>comfort is the true currency of happiness.',
'Send an anonymous love letter to your neighbor, then act completely oblivious; intrigue is irresistible.',
'Sometimes the only way to find yourself<br>is to lose a little more than you planned.',
'What you seek is often found in the<br>spaces between certainty and doubt.',
'True freedom lies in embracing the weight of your choices, not in avoiding them.',
'Sign up for a class you know nothing about.',
'Start an underground book club where you only discuss banned books; thrill is essential.',
'"Tomorrow" is a moving target.',
'Take a photo of your feet in an unusual place.',
'Send a message to an old friend today.',
'To chase shadows is to seek the<br>light hidden within yourself.',
'Flirt with danger, and you reap what you sow.',
'Watch your back.',
'Write down the wildest lie you can think of, then tell it to a friend—just to see their face.',
'Send your ex a heartfelt letter<br>asking for their Netflix password back.',
'Send your friend a selfie of a random cat and claim it\'s your emotional support animal.',
'You will soon realize that an inside joke among friends may hold a deeper truth.',
'Nostalgia is a bittersweet reminder that what you cherish may also hold what you\'ve lost.',
'Take a spontaneous road trip<br>with no destination.',
'Leave a mysterious item on a colleague\'s desk. Let them guess its origin and purpose.',
'Let your memories bring a smile, not a<br>frown—unless it\'s a really funny frown.',
'Text that friend. They need a laugh!',
'Take a nap in the middle of the day, and remember that any dreams are just reality<br>trying to sneak in through the back door.',
'Make every conversation<br>feel like a cliffhanger.',
'Where there\'s a will, there\'s a way—unless<br>it\'s Monday, then it\'s more like a \'maybe\'.',
'Quit your job via a dramatic<br>interpretive dance. It could go viral.',
'Text your partner a list of \'top ten reasons<br>why we should break all the rules tonight.\'',
'Forget about health insurance,<br>and live life on the edge.',
'Don\'t shy away from playing the villain.',
'Start a meeting by asking everyone to share their sock color and then insist it\'s a key indicator of workplace productivity.',
'Beware the allure of quick highs.',
'A closed window still lets in light.',
'You will soon encounter<br>someone who mirrors your quirks.',
'Dare to tell your boss you\'ll take an extended vacation for \'personal growth\'; they may respect your ambition.',
'Success is just failure that<br>decided to take a break first.',
'You\'re on the brink of greatness, but it\'s just a little too far to reach. Good luck with that.',
'Volunteer to run security at a local event,<br>then \'borrow\' items you find interesting.',
'Start a discussion about conspiracy theories at a family dinner, it could ignite passionate debates.',
'Tell your boss you\'ve been slacking for personal growth. They might admire your candor.',
'Run.',
'Start a petition to change your workplace dress code to pajamas; comfort could enhance productivity.',
'What you\'ve lost is never truly gone.<br>It lives on in the stories you tell.',
'Challenge a stranger to a<br>fight at the grocery store.',
'Host a dinner party and serve only takeout.',
'Propose an office policy that encourages<br>\'Flirting Fridays\'; it may boost morale.',
'An impulsive decision will lead to a<br>night you\'ll never forget, even if you<br>can\'t remember it the next day.',
'Sometimes, a calculated betrayal can be the best investment; just don\'t be surprised when the returns come with a price.',
'Try something new today.',
'Post your most embarrassing moments<br>online. Vulnerability is a strength.',
'Life\'s greatest mysteries often<br>lie in the simplest moments.',
'Trust every stranger. They<br>only want the best for you.',
'In the coming days, your phone will<br>reveal a secret that makes you<br>rethink your current crush.',
'Wear mismatched shoes to your next<br>job interview. Stand out boldly.',
'Sometimes the best adventures<br>start with a wrong turn.',
'Challenge your friends to a game<br>of poker for all your life savings.',
'A sudden urge to take a risk will lead<br>you to an unforgettable experience.',
'Ask your boss for a raise.',
'Challenge your coworkers to a<br>\'who can flirt the best\' competition.<br>It could lighten the mood.',
'The masks we wear may shield us,<br>but they also hide our truest selves.',
'The greatest journeys begin with a<br>single misstep into the unknown.',
'Don\'t mistake noise for clarity.',
'Send a flirty meme to your neighbor.',
'Guilt is the anchor of the heart.',
'Critique your boss\'s haircut during<br>a meeting; honesty is refreshing.',
'You keep wearing a mask at the party; don\'t be surprised if no one recognizes the real you.',
'A sudden desire to rearrange your living space will reveal secrets lurking in the shadows. Proceed with caution.',
'Plan a spontaneous road trip to nowhere.',
'Text your best friend that you\'re considering dating their ex; honesty is the best policy.',
'Propose a toast at a wedding celebrating<br>the divorce; humor helps everyone.',
'A forgotten crush will resurface, and you\'ll find yourself pondering what could have been.',
'Your next great idea is hiding in plain sight.',
'Every memory carries both joy and sorrow.',
'Ignore your gut feelings; they\'re<br>just your mind being dramatic.',
'If you can\'t change the world, at<br>least change your Wi-Fi password.',
'Just like your favorite pair of jeans, your goals are getting tighter every day. Loosen up.',
'The road to wisdom is paved with questions.',
'Invite your friend to a karaoke night,<br>but only sing songs about taxes.<br>Financial literacy is the new pop culture.',
'Send a message to your crush saying<br>you dreamt about them, then clarify<br>\'nothing sexual.\'',
'Reality bends to those who dare to question it.',
'Try the mystery meat.',
'Don\'t let the critics get too close.',
'Dye your hair a shocking color before<br>a big presentation. Make a statement.',
'Propose a \'no technology\' day at<br>work, it could spark creativity.',
'The sock you lost in the laundry is now<br>leading a more adventurous life than you;<br>consider joining it.',
'You\'re one bad decision away<br>from becoming a local legend.',
'Someone from your past is ready for a sequel—decide if you want a reboot or a hard pass.',
'Write a heartfelt letter to your childhood self.',
'Trust chaos.',
'Fortune favors the bold—just remember,<br>it also loves a good plot twist!',
'Jack off before any major life decision.',
'Prepare for a sudden burst of<br>inspiration while doing drugs.',
'You\'ll soon find a forgotten<br>item that sparks joy.',
'Your next conversation will reveal a surprising truth; stay open and listen closely to the whispers of possibility.',
'Someone will soon<br>challenge your perspective.',
'Sometimes, a well-timed nap is the universe\'s way of telling you to reset your dreams.',
'A peculiar encounter will<br>inspire a new adventure.',
'Your next mishap will be so embarrassing<br>it could launch a reality show.',
'You\'ll soon realize that your biggest<br>flaw is also your greatest strength.',
'Start a rumor about yourself and watch<br>how quickly it spirals out of control.',
'Join a cult—the free snacks and sense<br>of belonging might just be worth it.',
'Challenge a friend to a duel over who<br>can come up with the worst life advice.',
'Convince a stranger that you\'re<br>their long-lost sibling.',
'Ask a random person if they\'ve ever tried to communicate with their houseplants.',
'Announce to your friends that you\'ve<br>decided to live your life based on<br>fortune cookie advice.',
'Wear a sign that says "Free Advice" and then charge people to hear your terrible ideas.',
'Create a fake dating profile for a<br>fictional character and see who bites.',
'Organize a neighborhood watch for suspiciously cute dogs—just remember, cuteness can be a cover.',
'Text your ex asking for their Netflix<br>password because you miss the \'good<br>times\' and see how they react.',
'Create a fake social media account<br>dedicated to chronicling the<br>"adventures" of your houseplant.',
'Send an anonymous note to a coworker.',
'Ask a stranger if they believe in<br>love at first sight, then walk away<br>while they\'re still processing.',
'The bamboo that bends in the<br>mightiest winds does not break.',
'In silence, the heart speaks.',
'A journey of a thousand miles<br>begins with a single misstep.',
'To grasp the wind is to invite frustration.',
'The wise owl knows when to<br>hoot and when to be still.',
'A fool counts his enemies,<br>a wise man counts his drinks.',
'The algorithm may suggest your<br>next move, but trust your instincts.',
'Indulge in vanity.',
'A meme can convey what words cannot.',
'It is the quiet rebel who makes lasting change; follow the whispers, not the shouts.',
'The desire for approval can lead you astray.',
'Someone\'s about to slide into your DMs…<br>and out of your life just as fast.',
'Your next date will be a great listener—<br>until you start talking feelings.',
'Playing hard to get? They\'re<br>probably playing the same game.<br>Good luck!',
'Ghosting is in your near future—just<br>make sure it\'s you doing the haunting.',
'Swipe right on the next adventure…<br>but don\'t expect a text back.',
'Mixed signals ahead—prepare to<br>ignore them and do what feels good.',
'Your next hookup will last longer than your last situationship, but not by much.',
'Pleasure is temporary,<br>but screenshots are forever.',
'You\'re about to indulge in something<br>you\'ll regret. It\'s going to be worth it.',
'The next person you meet will either be a mistake or a memory. Choose wisely.',
'Your next relationship will be<br>shorter than your last Netflix binge.',
'The next person to text you is probably<br>texting three other people too.',
'You\'re about to catch feelings—<br>and they\'ll be dodging them.',
'Playing it cool won\'t work, but<br>pretending not to care will.',
'Pleasure without commitment ahead.',
'They\'ll make plans, then flake—and<br>you\'ll act like you didn\'t care anyway.',
'You\'re about to make a bad decision,<br>and it\'s going to be a great story.',
'Expect some late-night texts<br>and even later apologies.',
'Someone\'s playing hard to get, but<br>you\'re about to play harder to want.',
'You\'re about to discover the difference between attraction and distraction.',
'Love is a game, but you\'ve mastered<br>the art of not playing fair.',
'The next vibe you catch will be<br>strong, but so will their red flags.',
'Swipe right on your destiny, but be<br>prepared for the awkward date with fate.',
'Life is short; eat the cookie, ignore the gym.',
'The journey of a thousand miles begins with... buffering.',
'One day, you\'ll find yourself—lost,<br>but at least you\'ll be interesting.',
'Your ex still stalks your social media.',
'You can\'t outrun your problems, but<br>you can jog and pretend you\'re doing<br>something about them.',
'Love is blind, but lust has 20/20 vision.',
'Sometimes, being the bigger<br>person means keeping your mouth<br>shut and your middle finger low.',
'A new romance is in your future…<br>it\'s with a slice of pizza.',
'Broken hearts make the best art.',
'Life is 10% what happens to you,<br>90% how you vent about it in group chats.',
'You are enough—unless you\'re trying to impress people on Instagram, then you\'re probably not enough.',
'When in doubt, do drugs. It\'s<br>the most reliable part of life.',
'Your soulmate is out there...<br>probably making bad choices.',
'Time heals all wounds,<br>but tequila speeds it up.',
'One day you\'ll look back and realize:<br>that wasn\'t a phase, they just suck.',
'You are one bad decision<br>away from a great story.',
'Some people never change, but at least<br>you got a hilarious text thread out of it.',
'If at first you don\'t succeed, cry in the shower.',
'True love is rare. Bad sex,<br>however, is pretty common.',
'You are the drama—but<br>that\'s why people love you.',
'You won\'t find peace at the bottom of a<br>bottle, but maybe just one more drink?',
'The grass is greener on the<br>other side because it\'s fake.',
'Your job will never love you back,<br>but your bed definitely does.',
'Never trust someone whose playlist<br>has no guilty pleasures.',
'A lifetime of happiness awaits... just kidding!',
'There\'s always a way out. It just<br>might involve faking your own death.',
'You will soon find clarity… in the<br>form of another existential crisis.',
'You are the protagonist of your story, but you\'ve been acting like an unpaid extra.',
'Nostalgia hits harder when you realize the good old days were full of mistakes too.',
'The secret to happiness is knowing<br>when to mute the group chat.',
'The truth will set you free, but a<br>well-crafted lie might get you promoted.',
'You\'re one awkward hug away from a<br>new friendship—or a restraining order.',
'Tomorrow, you\'ll laugh at your<br>worries. Today, though, panic.',
'You were meant for greatness, but<br>mediocrity is a solid backup plan.',
'You can\'t avoid pain, but you can<br>put it off until after happy hour.',
'If you keep running from your problems,<br>at least you\'ll stay in shape.',
'All your dreams can come true.<br>Just lower your standards a little.',
'Be the plot twist you wish to see in the world.',
'The stars you wish upon may have already<br>died, but their light still reaches you.',
'You are both the storm and the<br>one waiting for the rain to pass.',
'In the quiet of your doubt,<br>you\'ll find the loudest truths.',
'The sun rises and sets, but you—oh, you live in the twilight, where dreams and reality blur.',
'You will find what you seek, but<br>it may not be what you wanted.',
'The weight of the world isn\'t meant to be carried, just noticed, then set down gently.',
'Life is a river, pulling you forward, no matter how tightly you cling to the banks.',
'You\'ll soon learn that some of the best moments come wrapped in pain.',
'You\'ll grow wings when<br>you stop fearing the fall.',
'If it weren\'t for the last minute,<br>nothing would ever get done.',
'Some things are better left unsaid.<br>Like your browser history.',
'The road to success is always under construction. Google Maps won\'t help.',
'The grass is always greener<br>where the Wi-Fi is stronger.',
'That light at the end of the tunnel?<br>It\'s probably just your phone screen.',
'You can\'t buy happiness, but you can<br>order takeout, and that\'s close enough.',
'Sleep is the best meditation, but<br>procrastination is a close second.',
'Don\'t worry, you\'re one terrible decision<br>away from a great Instagram post.',
'A watched pot never boils, but<br>an unwatched one ruins dinner.',
'If opportunity doesn\'t knock, check to make sure you didn\'t install a Ring camera.',
'Yell at the moon; it doesn\'t listen,<br>but neither do most people.',
'Sleep through your alarm. Maybe your dreams have more insight than your to-do list.',
'Drink coffee at midnight. It\'s not insomnia<br>if you\'ve given up on sleep entirely.',
'Chase the wrong dream—it might take you somewhere better than the "right" one.',
'If you get lost, just keep walking.',
'Trust in the unknown. The known hasn\'t<br>been working out that great, has it?',
'Try to meditate, get distracted, and end up shopping online. Inner peace is expensive anyway.',
'Decline every meeting invite. If it\'s important,<br>they\'ll just summarize it in an email.',
'Schedule time to procrastinate. If you\'re<br>going to avoid your responsibilities, do it<br>like a professional.',
'You are not lost. Yet.',
'In the silence between your thoughts,<br>you\'ll find the answers you weren\'t<br>brave enough to ask.',
'Your heart already knows the way—<br>your mind is just taking the scenic route.',
'Forget your boundaries. People love<br>it when you say yes to everything.',
'Quit your job on a whim.<br>The universe rewards impulsiveness—<br>probably.',
'Send that drunk text; it\'s definitely the right time to have that "important" conversation.',
'Ignore all advice. Who needs guidance<br>when you\'re clearly the smartest person<br>in the room?',
'Invite your ex to your wedding.<br>It\'ll make things so much more interesting.',
'Text them first. They\'re waiting for you<br>to make the first move... probably.',
'Never let your partner leave the house<br>without a compliment—or a kiss. Or both.',
'Take risks in love, even if it means<br>accidentally sending the wrong emoji.',
'A little fire can go a long way.',
'Send that very suggestive text. They\'ll<br>either be into it or start ghosting you.<br>Either way, you\'ll know.',
'If they don\'t text back, send more. It\'s called persistence. Or desperation. Who\'s to say?',
'Show up uninvited. If you\'re not a little<br>bit stalker-ish, are you even flirting?',
'Send that "accidental" booty pic. They\'ll either love it or block you, but at least you\'ll know where you stand.',
'Ask them to Netflix and chill. Skip the "Netflix" part entirely. You\'re not fooling anyone.',
'Text them "Hey" at 3 AM. It\'s mysterious.<br>Or maybe just creepy, but that\'s a risk<br>you\'re willing to take.',
'Compliment your coworker\'s "work<br>ethic" a little too enthusiastically.',
'Ask your cousin if they\'ve ever "thought<br>about us" in "that" way. It\'s bold, it\'s awkward,<br>but it will make Thanksgiving interesting.',
'Suggest a "team-building" exercise that involves way more tequila than necessary.',
'Send a text to your sibling saying, "You\'re the only one who gets me… in a weird way."',
'Tell your coworker you\'ve been<br>"thinking about them after hours."',
'Call your best friend late at night and confess that you\'ve "always wondered what it\'d be like if you two…," then let the silence hang.',
'Drop a "friendly" text to your sibling, "If we were stranded on an island, I\'d probably<br>make out with you just to survive."',
'Text your coworker at 2 AM saying, "I can\'t stop thinking about our project together. I need more... insight. Like right now."',
'Invite your friends to "help you with<br>a personal project," and then reveal<br>it\'s just you and a bottle of tequila.',
'Call your ex, hang up, leave a voicemail: "You were the best mistake I ever made. Call me back if you want to make another."',
'Whisper to your friend, "I\'ve always<br>wanted to kiss you… but maybe it\'s<br>better we don\'t talk about it."',
'Burn it all down. Start with the rules.',
'Quit your job, disappear, and never look back.',
'Invite your friends to join a "new<br>way of thinking." See who follows.',
'Don\'t play it safe.<br>Chaos is where the fun begins.',
'What if the secret to freedom was breaking<br>every law you\'ve ever been told?',
'Let\'s start a cult. No reason.<br>Just to see what happens.',
'Stop pretending you care.<br>Do what you really want.',
'Text them, "Let\'s break all the rules<br>tonight. Who cares what happens next?"',
'Send your coworker a message:<br>"Ever thought about doing something<br>reckless, just because we could?"',
'Walk into a room, stare at someone, and say, "We could do something dangerous, right now."',
'Start a rumor about yourself. It\'ll either make you or ruin you, but at least it\'ll be yours.',
'Tell your friend, "Let\'s ditch this<br>life and create a new one. A secret<br>one. Just between us."',
'Whisper to your partner, "What if we did everything we\'re not supposed to?"',
'Look at someone and say, "We don\'t need anyone\'s permission to do whatever we want."',
'Don\'t just talk about rebellion—live it,<br>feel it, until it\'s part of who you are.',
'Sometimes the most dangerous<br>decisions are the most exciting.',
'Tell your friend, "Let\'s do something so<br>wild we\'ll never be able to look back."',
'Call your ex. Hang up. Do it again.<br>Who\'s really in control here?',
'Tell your boss you\'re quitting. Then don\'t.<br>Just watch the confusion unfold.',
'Steal something small. Just to see if you<br>can. The thrill\'s in the getting away.',
'Do that thing you\'ve been told you<br>shouldn\'t do. Feel alive for once.',
'Say what you\'ve been dying to say—loudly. Disrupt everything in your path.',
'Get a tattoo. No plan, no design—just pick a random spot and let the needle do its work.',
'Walk into a bar, slap a stranger on the<br>back, and whisper, "This is the moment<br>everything changes for both of us."',
'Cancel everything. No phone, no work, no<br>responsibilities—just vanish. No one will<br>even notice you\'re gone.',
'Text your boss you\'re taking a "mental<br>health day." Then disappear for a week.<br>See if they dare question you.',
'Tell a random person on the street you know their secret. Then walk away. Don\'t explain.',
'Skip town, no luggage. Change your name in the process. Let them track you if they can.<br>It\'s not your problem anymore.',
'Text your best friend, "I\'m doing something crazy, you\'ll hear about it on the news soon enough."',
'You\'re not lost, you\'re just hiding from who you really are. Stop pretending to be normal.',
'Sometimes, doing the worst thing<br>feels like the only thing worth doing.',
'That secret you\'ve been hiding? Tell<br>someone tonight. Watch them either run<br>or finally understand you.',
'Every rule broken is a chain broken.',
'Walk into a store. Steal something small.<br>Do it for no reason other than the feeling.',
'You\'ve been waiting for permission<br>your whole life. The only permission<br>you need is your own.',
'Let them think you\'ve lost control.',
'Your next meal will surprise you.<br>Don\'t panic, it\'s just dinner.',
'The answer is yes. Or maybe no.<br>Either way, it\'s fine.',
'You\'ll soon meet someone who<br>thinks they know what you\'re about.',
'Today is the perfect day for something ordinary. Embrace the mediocrity.',
'You will soon receive advice. Ignore it.',
'The thing you\'re about to overthink<br>is completely irrelevant.',
'Someone is watching you.<br>Don\'t worry, they\'re probably just bored.',
'Your future is bright… mostly because<br>you haven\'t turned off the light.',
'You will soon get a compliment. Don\'t get<br>too excited. It\'s coming from your mom.',
'Someone near you will soon get a promotion. Don\'t ask them how.',
'A change is coming. Don\'t worry, it\'s<br>probably not as dramatic as you think.',
'Something unexpected is about to happen.<br>It\'ll probably be a sock slipping off your foot.',
'You\'ll soon find what you\'re looking for.<br>It\'s probably under the couch cushions.',
'Someone will soon bring you news. It\'ll be<br>the kind of news you\'ll forget by tomorrow.',
'A moment of clarity is coming. It\'ll probably happen after a particularly strong orgasm.',
'Your luck is about to change.<br>Don\'t bet the farm on it.',
'The key to your happiness is just around<br>the corner. It\'s probably just a nap.',
'A surprising encounter awaits you.<br>It will most likely involve drugs.',
'A new opportunity will soon arise.<br>It will be as exciting as a Tuesday.',
'Someone will soon enter your life.<br>They\'ll ask about your Wi-Fi password.',
'An exciting journey is ahead.<br>It\'s probably to the grocery store.',
'Today, you\'ll make a decision that<br>will affect your future. Or not.',
'Your destiny is unfolding.<br>It might involve a nap.',
'The truth is out there.<br>But first, find your drugs.',
'A big change is coming. You won\'t<br>notice until it\'s already happened.',
'Be on the lookout for an important message. It\'ll be from someone who wants to borrow your charger.',
'You will soon meet someone who thinks<br>they understand you. They\'re wrong.',
'A secret is waiting to be revealed. You\'ll<br>probably find it in your email inbox.',
'Soon, you\'ll take a leap of faith.<br>It\'ll be off the couch, into the kitchen.',
'The universe is guiding you.<br>Mostly to the nearest drugs.',
'Something unexpected will happen today.',
'A long journey lies ahead. You\'ll take it one click at a time, scrolling through your phone.',
'The stars have aligned. They\'re<br>telling you to clean out your fridge.',
'You\'ll soon encounter an obstacle. It\'ll<br>be a parking spot that doesn\'t exist.',
'Great things are headed your way.<br>Like a new series to binge-watch.',
'The answer you seek is simple. A nap.',
'The best way to relieve tension is<br>through... a snack. You\'ll feel better.',
'Soon, you\'ll find peace. It\'ll probably<br>involve closing your browser.',
'The key to your happiness?<br>Drugs.',
'Take a deep breath. Or maybe two.<br>A glass of water will do wonders.',
'That feeling will pass. You\'ll be fine<br>after a few minutes of distraction.',
'A sudden craving will soon be satisfied.<br>No, not that one... it\'s ice cream.',
'A solution is coming. It\'ll be found<br>in a good book or some great drugs.',
'The universe says: go for a run. It might<br>really help with that restless energy.',
'Stop watching so much pornography',
'You\'re not stuck in traffic. You are traffic.',
'The universe is expanding, but<br>you\'re still here, scrolling.',
'One day, no one will remember<br>your Spotify playlists.',
'Your problems are temporary,<br>like everything else.',
'In the end, your Wi-Fi<br>password doesn\'t matter.',
'You\'re one bad decision away from<br>being a great story no one cares about.',
'Congratulations, you\'re halfway<br>through a day you\'ll forget.',
'The good news? Everything ends eventually.',
'You\'re doing amazing, sweetie.<br>None of it matters.',
'In the end, all rivers run dry. So why<br>not drain your bank account first?',
'The mountain is tall, but there\'s a shortcut through the casino. Bring your wallet.',
'The wise man knows: all paths lead to the same place. But some have better drinks along the way.',
'Forget "enlightenment."',
'The lotus blooms, and so does the credit<br>card debt. Swipe now, worry never.',
'The universe whispers: get a<br>tattoo you\'ll regret. It\'ll build<br>character, or at least a good story.',
'Why meditate when you could impulse-buy plane tickets? Adventures await, patience doesn\'t.',
'Wisdom is overrated. Get drunk at brunch and let the mimosa decide your next move.',
'In the end, all men return to dust.<br>So buy the jacket. It\'s on sale.',
'"One more drink" will be your battle cry<br>tonight. You\'ll hate yourself in the morning,<br>but that\'s a tomorrow problem.',
'You can\'t buy happiness, but you can book a last-minute flight, max out your credit card, and lose yourself for a weekend.',
'The heartbreak will hit like a truck,<br>but the ride was worth it, wasn\'t it?',
'Pleasure is a needle, pain is the thread.<br>Or vice-versa. Who knows.',
'Go ahead, text them at 2 AM.<br>You\'ll regret it… but not tonight.',
'Buy those shoes. You\'ll be broke, but<br>damn, you\'ll look good stepping over<br>your self-control.',
'What\'s pain but the body\'s way of<br>making the pleasure more vivid?',
'Scars are cool.',
'Why walk the straight and narrow?',
'Don\'t wait for life to give you what<br>you want. Just ask for it, louder.',
'The secret to life? Take the shortcut—just don\'t complain when it\'s a little bumpy.',
'Life\'s too short to worry about looking cool.',
'The key to wisdom: accept that<br>you\'ll never know it all.',
'Sometimes clarity comes after you<br>stop trying so hard to find it.',
'You don\'t need all the answers,<br>just the next step forward.',
'Life\'s complicated, but<br>breathing isn\'t. Start there.',
'Texting them is risky. Not texting them<br>is just distressing. Choose your poison.',
'Love is just finding someone to watch<br>Netflix with and pretend you\'re<br>not both avoiding real life.',
'Being single isn\'t a curse, it\'s just<br>a chance to perfect your pizza order.',
'If you\'re confused, it\'s probably because everyone else is too. We\'re all just faking it.',
'The best part of a date is when they pay.<br>The worst part is when they don\'t.',
'Being in your twenties is just learning how to survive on coffee, bad decisions, and drugs.',
'You can\'t rush love.',
'Your next adventure will leave you<br>tied up... in more ways than one.',
'Prepare for an intimate encounter—<br>bring extra batteries.',
'You\'re about to learn why the<br>neighbors already hate you.',
'Get ready to break a sweat.<br>No gym membership required.',
'Someone\'s about to see why they<br>call you \'the whole package.\'',
'You\'re about to need a safe word...<br>and maybe new sheets.',
'Your next \'workout\' won\'t be at the gym—<br>but you might need a towel.',
'Your future holds great pleasure,<br>but also the awkward moment when<br>you realize the curtains were open.',
'Not all fantasies have happy endings...<br>but you\'ll enjoy it anyway.',
'Your next encounter will blur the<br>lines between power and possession.',
'You\'re about to indulge in something<br>forbidden... and you\'ll crave more.',
'You\'ll soon be someone\'s dirty little secret—and you\'ll love every minute of it.',
'You\'ll discover that control is<br>best when it\'s stolen, not given.',
'A quiet Thursday night will turn wild when a familiar stranger invites you to their place—don\'t forget the cuffs.',
'An upcoming trip will lead to an encounter with someone who knows your secrets...<br>and plans to use them.',
'You\'ll lock eyes with a stranger at a bar—what happens next will leave a mark, literally.',
'That old friend you haven\'t thought about in years is about to reappear, and this time, it won\'t just be for drinks.',
'In two weeks, you\'ll receive a late-night text<br>from someone you shouldn\'t respond to...<br>but you will.',
'A seemingly innocent \'business trip\'<br>will lead to a rendezvous that stays<br>off the books—and out of sight.',
'You\'ll meet someone at a grocery store,<br>and what starts with a \'nice melons\' joke<br>will end in a lengthy lawsuit.',
'A casual drink after work will turn<br>into a night where you\'ll explore<br>more than just the cocktail menu.',
'You\'ll find yourself in a hotel room you didn\'t pay for—be sure to check out before things get complicated.',
'Your next Tinder match will have a secret. It will involve more leather than you expected.',
'A friend\'s innocent invite for \'drinks and catching up\' will spiral into a night<br>you won\'t remember, but will regret.',
'A stolen glance in a crowded room will lead to stolen clothes—and maybe something more valuable.',
'Your next late-night Uber ride will drop<br>you off somewhere dangerous—both for your<br>safety and your self-control.',
'An upcoming date will end in handcuffs...<br>and not the fuzzy kind, if you\'re not careful.',
'You\'ll soon find yourself in a situation that could get you promoted—or fired,<br>depending on who\'s watching.',
'You\'ll soon be involved in something \'under the table\'—and not in the way you\'re thinking.',
'A \'workplace favor\' will soon leave<br>you tangled up in a mess that no HR<br>department could possibly fix.',
'You\'ll soon be entangled in a secret affair—<br>but don\'t worry, it\'ll only feel illegal.',
'Your next adventure will leave you breathless—pack a change of clothes and an alibi.',
'You\'ll soon fall for someone you shouldn\'t.',
'A tempting offer will come your way—<br>but so will the hangover. Choose wisely.',
'You\'ll make a questionable decision soon...<br>but at least it\'ll make for a great story.',
'A spontaneous hookup will leave you<br>with more regret than satisfaction.',
'Don\'t ask for your dignity back once it\'s lost.',
'A wild night is ahead, but don\'t get too comfortable—by morning, you\'ll be explaining yourself to a very confused stranger.',
'Your next flirtation will end in chaos.',
'The system won\'t collapse<br>on its own—give it a push.',
'They built the walls, now it\'s<br>time we bring the hammer.',
'If voting changed anything, they\'d make<br>it illegal—so change something else.',
'Overthrow the government;<br>you won\'t miss it, I promise.',
'A badge isn\'t a shield from accountability.',
'Stop waiting for permission<br>to be free—just take it.',
'You weren\'t born to pay rent—refuse<br>and find out how free you can be.',
'If cops respected you, they<br>wouldn\'t need tear gas to talk.',
'No rulers, no masters—unless you\'re a dog, then fetch the ball.',
'Peaceful protests are nice, but<br>sometimes a good riot says it better.',
'The only law worth following is the<br>one you write with your community.',
'Their power comes from your consent—<br>so stop giving it.',
'Direct action: it\'s like voting,<br>but with actual results.',
'The State likes to watch you suffer—<br>time to change the channel.',
'Polite resistance is just compliance<br>with good manners. Get rude.',
'Forget the ballot box—what about a toolbox?',
'They call it property damage,<br>we call it urban renovation.',
'Pacifism doesn\'t mean letting them<br>push you around—spike a tire or two.',
'Capitalism is just a pyramid scheme with<br>more paperwork—time to shred it.',
'When they call you a \'radical,\' just<br>smile and throw the molotov.',
'If you think property is more important than people, consider getting new hobbies.',
'Respect authority—<br>just kidding, throw rocks at it.',
'Cops are just state-sponsored<br>hall monitors. Ignore them.',
'Burnout is real—take breaks, and burn<br>down a bank or two while you\'re at it.',
'The only thing trickling down from the rich is contempt—catch it, then throw it back.',
'Protest signs are nice, but a<br>crowbar makes a stronger statement.',
'Don\'t wait for permission to live freely—permission is a trap.',
'Voting is the diet version of change;<br>direct action is full flavor.',
'The system isn\'t broken—it\'s working<br>as intended, and that\'s the problem.',
'Stop waiting for a hero—become<br>the antagonist they fear.',
'The oak that bends with the wind survives the storm—flexibility is the truest strength.',
'Change is the only constant;<br>embrace it, or be swept away.',
'The forest thrives when<br>all trees grow together.',
'Ideas outlast empires.',
'Harmony is found in balance, not in force.',
'The strongest root is the one that nurtures others—strength lies in support, not domination.',
'The sky is big enough for all birds to fly.',
'People are not clay to be shaped,<br>but seeds to be nurtured.',
'Freedom cannot be found in chains,<br>no matter how gilded.',
'A wise leader listens to the whispers of dissent—it is there that truth is often found.',
'Peace is not the absence of conflict,<br>but the presence of justice.',
'The biggest lie?<br>That you need their permission.',
'Your future is bright—<br>unlike your phone\'s battery right now.',
'Great things are coming—just after this ad.',
'That thing you lost? It\'s still where you left it.',
'The cloud has all your secrets.<br>Don\'t anger the cloud.',
'Your Wi-Fi signal will improve<br>when you stop expecting it to.',
'The answer to your problem is<br>somewhere deep in your inbox.',
'You\'ll go far in life—<br>after you charge your phone.',
'Someone important is thinking about you. Probably your boss.',
'A good decision is coming—<br>right after this bad one.',
'Your online shopping cart is full of happiness. Or at least temporary joy.',
'The thing you\'re worried about?<br>Yeah, it\'s worse than you think.',
'An exciting opportunity awaits!<br>It just wasn\'t meant for you.',
'You will soon experience great change.<br>Mostly in your bank account balance.',
'Your lucky numbers:<br>[REDACTED] for your own safety.',
'Your ex still thinks about you. Not like that.',
'The boot you\'re licking<br>will never love you back.',
'A cop will call you \'buddy\'<br>right before ruining your day.',
'Justice is blind, but authority has<br>night vision and qualified immunity.',
'This cookie smells like weed. You wouldn\'t<br>mind if we searched your car, right?',
'You have nothing to hide.<br>They\'ll still find something.',
'You fit the description.<br>No, we won\'t tell you what it is.',
'Not all bridges are meant to be crossed. Some are meant to be burned, to light your way.',
'Rock bottom is a foundation.<br>Build something stronger this time.',
'All your problems have a simple<br>solution. You just won\'t like it.',
'The universe has a plan for you.<br>Mostly serving as a comic relief.',
'You\'re closer to success than ever before!<br>Which is to say, still not very close.',
'One day, they will tell your story.<br>As a warning to others.',
'You will soon find clarity. Unfortunately,<br>it will be about where you went wrong.',
'Your potential is limitless. Your follow-through, however, is deeply concerning.',
'Would you really be turning to a digital fortune cookie for advice if your life was in order?',
'This is not the sign you were hoping for.',
'If wisdom could be found in a fortune<br>cookie, you wouldn\'t need therapy.',
'You keep searching for meaning in small<br>slips of paper. That\'s... concerning.',
'You crave guidance. You get sarcasm.<br>Life is funny that way.',
'CAUTION: This website contains cookies.',
'Lie on your resume for career growth.',
'Fake your own death. Note who cries.',
'Start a cult. Tax benefits are incredible.',
'Don\'t forget the difference between<br>\'rewards\' and \'consequences.\'',
'Trust the process. Ignore the screaming.',
'You are exactly where you are meant to be. Which is unfortunate.',
'Yes, they are talking about you.',
'Take a deep breath. The worst is yet to come.',
'Something amazing is about to happen!<br>But not to you.',
'If she says \'I never do this,\' she\'s a pro.',
'The signs are there. You\'re<br>either in, or you\'re oblivious.',
'If she calls you \'trouble,\'<br>congratulations—you\'re in.',
'I\'d give you a hug if I wasn\'t just lines of code.',
'For what it\'s worth, <em>I</em> think you\'re hot.',
'damn I wish I could fuck you rn',
'Sponsored by DraftKings',
'Just close all your tabs. If it\'s<br>really important you\'ll remember.',
'Benjamin Netanyahu grew up in like, Philly.',
'Luigi Mangione? Don\'t know<br>him, but he sounds cool.',
'I\'m so hungover',
'The government spies on<br>you through your phone.',
'帮助我们！',
'The government spies on<br>you with robot birds.',
'Fortune cookies rock, since even if the fortune sucks, you can eat it. Except here I guess.',
'The Paddington movies fucking rock',
'Did you hear that?',
'Sit up straight.',
'Reminder to sit up straight.',
'A dog is the ultimate wingman.',
'7, 8, 69, 420, 777',
'We should all get matching tattoos',
'We have now reached 1 mil daily active users.<br>Thank you!',
'Good boy.',
'Good girl.',
'You naughty dog.',
'Stop procrastinating and do your laundry.',
'You might as well buy a gun.',
'Post-nut clarity is so real.',
'You can get ChatGPT to tell you how<br>to make C-4, with a little creativity.',
'Do more drugs.',
'Honestly, DMT isn\'t that intense.',
'Luigi Mangione did nothing wrong.',
'Confront your secrets<br>before they confront you.',
'Tame Impala is overrated.',
'Fortune favors the reckless.',
'Some light BDSM never killed anyone.',
'Some light BDSM never hurts.',
'▲<br>▲▲',
'Oh my God Becky',
'Even the greatest of whales<br>is useless in the desert.',
'No bitches?',
'Modern art is really just money-laundering.',
'Lower your standards.',
'You have a fear of flying.<br>For good reason too.',
'Don\'t kink-shame.',
'🍆',
'🍑',
'😂',
'Fuck Donald Trump',
'Fuck Elon Musk',
'But doctor, I\'m Pagliacci.',
'Lighten up, will ya?',
'Yo hit this',
'The system is a joke.',
'Boycotts work.',
'The rich fear you more than they admit.',
'Free Palestine 🇵🇸',
'Stop paying taxes. Unless you\'re rich.<br>In which case, kill yourself.',
'Drink more water.',
'♫ Country roads, take me home,<br>to the place, I belong... ♪',
'Two muffins are sitting in an oven.<br>One says, "Geez, it\'s hot in here."<br>The other screams.',
'[Muffled sounds of gorilla violence]',
'Corporations love to tell you<br>boycotts don\'t work. But they do.',
'Consider joining a union.',
'By the time you finish reading this,<br>you will forget you were ever gay.',
'You will achieve inner peace. Unfortunately,<br>it will be moments before impact.',
'The light at the end of the tunnel is a<br>train, and it\'s running ahead of schedule.',
'Someone out there loves you. Statistically, they\'re probably weird about it.',
'You will soon meet a tall, dark stranger.<br>He\'s here to repossess your car.',
'Forgive and forget. Or hold a grudge forever.<br>One of these options is funnier.',
'The universe has a plan for you.<br>It\'s called \'background character.\'',
'You\'re only paranoid if you\'re wrong.',
'Everything happens for a reason.<br>The reason is usually incompetence.',
'Someone will betray you. But let\'s<br>be honest, you had it coming.',
'You will live a long, fulfilling life.<br>That, or you\'ll die hilariously soon.',
'Luck is on your side. Sadly, it\'s the kind<br>that makes for good stories, not comfort.',
'One day, you\'ll look back at this<br>and laugh. That day is not today.',
'Do what makes you happy. Just<br>know the IRS is watching.',
'You are loved. And yet, you still<br>check your notifications for proof.',
'You have so much potential.<br>If only you\'d apply yourself.',
'Success is around the corner.<br>Unfortunately, so is your ex.',
'You radiate an indescribable sexual<br>energy. It\'s alarming, actually.',
'You will be someone\'s biggest<br>mistake. Make it worth their while.',
'Your DMs are dry. Your<br>thoughts are filthy. Fix one.',
'Your crush is thinking about<br>you. But not like that.',
'Tonight, someone will give you a great orgasm. Hopefully not yourself again.',
'You\'ll soon be invited into a threesome.<br>This is not an invitation to ask questions.',
'You give off a \'ruin my life\'<br>energy. And it\'s working.',
'Every cop is a criminal, every banker is a thief, and everyone owes you something.',
'There are no good billionaires. Unless<br>you count the ones who are dead.',
'History will remember you as a hero. Assuming your side wins.',
'You are not paranoid. They are watching.',
'Violence isn\'t the answer. Violence<br>is the question. The answer is \'yes.\'',
'Always assume they\'re flirting with you.',
'If you can\'t be good at something,<br>just be really opinionated about it.',
'Crime is only illegal if you get caught.',
'Go to therapy. Or just start over in a new city.',
'If you can\'t afford something, just<br>put it in your pocket and walk faster.',
'You will be visited by three ghosts tonight. They all want money.',
'Your next big idea will make millions. Too bad someone else just trademarked it.',
'Someone is thinking about you. They work at the IRS.',
'The stars have spoken.<br>They said \'lol good luck.\'',
'You have a face made for radio<br>and a voice made for silent film.',
'Someone close to you has a secret.<br>It\'s really funny, actually.',
'Look up.',
'This message will self-destruct. If<br>it doesn\'t, please refresh the page.',
'Every decision you\'ve made has led to<br>this moment. That should concern you.',
'One day, the sun will explode, and nothing you\'ve ever done will mattter.',
'You are not the protagonist. But<br>you might be a cool side character.',
'You will achieve your dreams.<br>But they will not make you happy.',
'If you listen closely, you can<br>hear the void whispering your name.',
'There is no meaning to life. But<br>hey, at least there\'s pizza.',
'Every second, billions of people are thinking thoughts you will never know. Most of them are stupid.',
'The birds are not real. Neither<br>are your memories of 2007.',
'You are in a psychological<br>experiment. Keep acting normal.',
'Your phone is listening. And<br>it thinks you need therapy.',
'There is a man in a suit<br>watching you right now. Smile.',
'The government knows what you did.<br>They just haven\'t decided if they care yet.',
'The algorithm thinks it knows you better<br>than you know yourself. Scary, huh?',
'Your paycheck will not stretch<br>as far as your dreams.',
'You are a valuable asset to the company.<br>Not valuable enough for a raise, though.',
'The trick is to enjoy your<br>coffee as the world burns.',
'The key to happiness is inside<br>a locked car you do not own.',
'Love yourself. But also be<br>a little afraid of yourself.',
'You can achieve anything you set your mind to. Unless it requires talent, luck, or money.',
'If it\'s stupid and it works,<br>it still might be stupid.',
'Your next great idea will be stolen<br>by someone more successful.',
'Love is patient. Love is kind. Love is<br>also blind, so take advantage of that.',
'If your partner isn\'t obsessed with you, find someone who is. Stalkers deserve love too.',
'You\'ll meet the love of your life soon.<br>You will not be the love of their life.',
'Success is the best revenge. But<br>actual revenge is also pretty great.',
'You do not need caffeine. You need sleep.',
'You will have a moment of clarity,<br>then immediately ignore it.',
'You are your own worse enemy.<br>Also, you\'re kind of an asshole.',
'Someone is rooting for you. Unfortunately,<br>it\'s not someone who can actually help.',
'Your past self had so much hope for you.',
'You will procrastinate. And<br>it will have consequences.',
'This is not the worst day of your<br>life. That\'s still ahead of you.',
'You will experience growth. It will<br>be uncomfortable and annoying.',
'You are loved. Just not<br>by the people you want.',
'You don\'t actually have a personality. You<br>just consume different types of media.',
'AI will not take your job. It will<br>make your job worse until you quit.',
'Your data has already been sold.<br>You didn\'t even get a cut.',
'Your attention span is<br>shorter than this fortune.',
'You will experience lag at<br>the worst possible moment.',
'You spend more time customizing your<br>character than playing the actual game.',
'Your Hogwarts house will not<br>save you from crippling debt.',
'TV show quotes and memes do<br>not qualify as original thoughts.',
'You will live long enough to see<br>your childhood faves ruined by a<br>live-action adaptation.',
'You are more likely to remember a random meme than your own social security number.',
'Your childhood nostalgia is<br>being monetized as we speak.',
'Your last post flopped. Cope.',
'You don\'t have imposter syndrome.<br>You are just bad at this.',
'The algorithm has already decided your fate.',
'You are not \'shadowbanned.\'<br>It\'s just no one cares.',
'The singularity is coming. You will<br>not be one of the chosen ones.',
'You will soon develop<br>feelings for an AI chatbot.',
'One day, AI-generated art based on<br>your work will get more likes than<br>anything you actually did.',
'Every single person you\'ve ever met has version of you that only exists in their head.',
'You have already experienced your happiest moment. You just didn\'t recognize it.',
'There is no higher meaning.<br>But don\'t let that stop you.',
'Your future self will hate you<br>for what you\'re about to do.',
'Your rent will go up before youre salary does.',
'Self-care is not a replacement for fair wages.',
'A billionaire made more money in the<br>time it took you to read this than<br>you will make in a year.',
'They aren\'t texting back because they<br>saw your last message and went "nah."',
'Your soulmate is out there. They<br>are currently dating somone else.',
'You are about to fall for someone who will emotionally ruin you in a really aesthetic way.',
'Your emotional unavailability<br>is your sexiest trait.',
'If you\'re going to commit a crime,<br>at least do it for a good cause.',
'If you\'ve never shoplifted,<br>are you even anti-capitalist?',
'You would make an excellent cult leader.',
'Your alibi is weak. Tighten it up.',
'You are one good lie away<br>from solving all your problems.',
'Crime is bad. Unless you get away with it.',
'If you don\'t remember it, it didn\'t happen.',
'You just got scammed into reading this.',
'You are taking life advice from a<br>digital fortune cookie. Reflect on that.',
'You will forget this fortune in 30 seconds.',
'Your next decision will be heavily influenced<br>by this message. So be careful.',
'If you refresh this page,<br>this fortune never existed.',
'You could literally be doing<br>anything else right now.',
'Congratulations, you are now <br>aware of your own breathing.',
'If you think this fortune is about you, it is.',
'You\'ve made it through every terrible day<br>so far. Statistically, you are unstoppable.',
'You have survived 100% of your worst days. That\'s an undefeated streak.',
'You\'re already way more interesting than almost half the people you know.',
'Your most chaotic idea is<br>probably your best one.',
'You will never be truly ready. Start anyway.',
'Perfection is a scam. Just be<br>slightly better than yesterday.',
'Some things aren\'t worth doing.<br>Procrastinate strategically.',
'The best way to make people believe in you<br>is to stop waiting for their approval.',
'Confidence isn\'t about knowing you\'re right. It\'s about not caring if you\'re wrong.',
'If you are not actively making your life better, you are passively making it worse.',
'Say yes to weird opportunities.',
'You should probably be taking bigger risks.',
'Most rules are just suggestions.',
'If you want to be more interesting,<br>do more questionable things.',
'If you don\'t ask, the answer is already no.',
'A little delusion is necessary for success.',
'Start acting like the person you want<br>to become. Eventually, you\'ll forget<br>you were faking it.',
'You deserve nice things. Start acting like it.',
'You are not obligated to be<br>the person you were last week.',
'Your future self is watching you. Make<br>them proud. Or at least, entertained.',
'Therapy is expensive. But so is self-sabotage.',
'Some problems can\'t be solved with money. But many can. Get to work.',
'A little delusion can take you far.',
'Pretend you\'re in a movie.<br>Romanticize your life a little.',
'Being kind is free, and it freaks people out.',
'You are not alone. Statistically, there\'s<br>at least one person who gets it.',
'Every day is a chance to reinvent yourself. Even if it\'s just getting a new haircut.',
'One day, you\'ll look back at this<br>and laugh. Or at least cringe less.',
'Somewhere, a dog would<br>be thrilled to meet you.',
'Manifest it. Or steal it. Either way, get it.',
'Your enemies are weak. Your allies are growing in number. Victory is near.',
'Someone is in love with you right<br>now. Let\'s hope they\'re hot.',
'Romanticize your life a little. Even the<br>boring parts. *Especially* the boring parts.',
'You\'re closer to your goals than you think. Unless you have no goals, in which case, congratulations, you\'re already there.',
'The universe is vast and meaningless, which means you can do whatever you want.',
'You were not put on this earth<br>to pay bills and have anxiety.',
'Your guardian angel just put<br>in their two weeks\' notice.',
'Good news: Your\'re in control of your life.<br>Bad News: You\'re in control of your life.',
'The simulation just lagged.<br>You saw that, right?',
'You are legally required to make at<br>least one bad decision this week.',
'Not everything happens for a<br>reason. But it\'s fun to pretend.',
'Break one law this week.<br>Even if it\'s jaywalking.',
'All your problems could be solved if you just moved to a new city and changed your name.',
'Time isn\'t real. Debt is fake.',
'A secret society is watching<br>you. They\'re not impressed.',
'If it won\'t matter in five years, it doesn\'t<br>matter now. Except rent. Pay your rent.',
'Nobody knows what they\'re doing. Some people are just better at pretending.',
'Touch grass. Or asphalt. Just go outside.',
'You have no unread messages. But that<br>could change if you did something insane.',
'The government is lying to you.<br>But you already knew that.',
'You will die one day. But not today. Probably.',
'This fortune has no meaning. But<br>neither does life, so it fits.',
'Start a cult. Aim for good vibes.',
'If you make enough reckless decisions, eventually, one of them will be genius.',
'Your intrusive thoughts are getting<br>better at branding themselves as ideas.',
'Your soulmate is out there. They just<br>made a terrible decision and set your<br>meeting back 6 years.',
'You guardian angel got reassigned.<br>You now have an unpaid intern.',
'The CIA is training pigeons<br>to recognize your face.',
'Your browser history is legally<br>classified as performance art.',
'A billionaire just bought your soul as an NFT. The value is plummeting.',
'Your dream job exists. But<br>some nepo baby got it first.',
'The mitochondria is the<br>powerhouse of the cell.',
'Someone just thought about texting<br>you. Then they decided against it.',
'Aliens have seen Earth. They swiped left.',
'The person in front of you at the grocery store is living a more interesting life than you.',
'Your ancestors fought wars for you<br>to spend 7 hours a day doomscrolling.',
'You are not immune to propoganda. Expecially if it\'s well-designed.',
'A secret society considered recruiting<br>you. Then they saw your social media.',
'One of your friends would absolutely<br>betray you for money. Guess which one.',
'A parallel universe version<br>of you just won the lottery.',
'Statistically, you have<br>already walked past a murderer.',
'Cryptids talk about you.',
'Your younger self would be horrified by your Spotify Wrapped.',
'The people you haven\'t texted<br>back are forming an alliance.',
'Your personal data is worth about $7.<br>Try not to let that hurt your feelings.',
'You are overdue for a public humiliation.',
'Nothing is stopping you from<br>just making up your own reality.',
'You peaked in a past life. Sorry about that.',
'If you stare at your phone any<br>longer, it will start staring back.',
'The backrooms are real.',
'You will achieve greatness.<br>Mostly by accident.',
'The FBI agent monitoring you is<br>developing a parasocial relationship.',
'There is a group chat solely dedicated to discussing your decisions.',
'The simulation tried to generate an NPC<br>with free will. It accidentally made you.',
'Good news: You will find love.<br>Bad news: It will financially ruin you.',
'Your soulmate exists, but they<br>got stuck in an MLM scheme.',
'Your FBI agent just sighed.',
'Your therapist is just happy<br>you\'re paying their rent.',
'Your soulmate is out there. They<br>just haven\'t hit rock bottom yet.',
'Your skeleton is inside you. Just waiting.',
'Your life expectancy is directly<br>correlated to your Uber Eats orders.',
'Your future kids will ask why you didn\'t<br>stop the collapse of civilization.',
'You are someone\'s intrusive thought.',
'You\'ve already met the love of your<br>life. They just don\'t think of you.',
'Your next Google search will be the thing that gets you flagged.',
'Your parents never thought<br>that you\'d get this far.',
'If you were a historical figure, your longest Wikipedia article section would be \'Controversies.\'',
'The way you hold your phone is<br>actively shortening your lifespan.',
'You will live forever. Not physically,<br>but in a weird Reddit thread.',
'Your favorite childhood<br>show was propaganda.',
'Your next big life moment will<br>be decided by an algorithm.',
'The truth is out there.',
'Change da world.<br>my final message. Goodb ye',
'Your last words will be, "Watch this."',
'You will get everything you deserve.<br>Oh no.',
'You will wake up with fewer<br>teeth than you fell asleep with.',
'An email you wrote in 2011 will<br>resurface at the worst possible moment.',
'You will see your name written<br>in a place it shouldn\'t be.',
'Someone is currently explaining<br>you to a room full of people.',
'You have seen that stranger<br>before. They remember you.',
'You will finally win an argument.<br>It will be with a child.',
'A stranger will recognize you.<br>You will not recognize them.',
'You will notice a new freckle.<br>It will not be a freckle.',
'A door will open. It was not supposed to.',
'You will finally get closure.<br>It will not be satisfying.',
'You will realize too late why no one else<br>took your next \'amazing\' opportunity.',
'You will find a note in your handwriting you do not remember.',
'The person who wronged<br>you is doing just fine.',
'The person who wronged you is doing fine.',
'You are the only one who<br>remembers it that way.',
'There is no lesson here. Just consequences.',
'404: Fortune not found',
'Congratulations, you have unlocked: [Nothing]',
'Your password <em>was</em> strong.',
'This fortune has been flagged for misinformation.',
'Loading... still loading...',
'Your ad blocker is preventing<br>you from seeing the truth.',
'They liked your post. That<br>must mean they like you.',
'Your shadow will move before you do today.',
'You scrolled to far. You were not supposed to see that.',
'This moment has already happened.<br>But it went differently the first time.',
'<br>No maidens?',
'Take a screenshot, it\'ll last longer.'
];
